/*
class Task {
  String title;
  String description;
  String timeAndDate;
  String priority;
  bool isChecked;

  Task({
    required this.title,
    required this.description,
    required this.timeAndDate,
    required this.priority,
    required this.isChecked,
  });
}
*/
class Task {
  int? id; // Add the 'id' field
  String title;
  String description;
  String timeAndDate;
  String priority;
  bool isChecked;

  Task({
    this.id, // Make the id optional so it can be auto-generated by SQLite
    required this.title,
    required this.description,
    required this.timeAndDate,
    required this.priority,
    required this.isChecked,
  });

  // Convert a Task into a Map (for SQLite)
  Map<String, dynamic> toMap() {
    return {
      'id': id, // Include the id in the map
      'title': title,
      'description': description,
      'timeAndDate': timeAndDate,
      'priority': priority,
      'isChecked': isChecked ? 1 : 0, // Convert boolean to integer (1 or 0)
    };
  }

  // Convert a Map into a Task (from SQLite query result)
  factory Task.fromMapObject(Map<String, dynamic> map) {
    return Task(
      id: map['id'], // Extract id from map
      title: map['title'],
      description: map['description'],
      timeAndDate: map['timeAndDate'],
      priority: map['priority'],
      isChecked: map['isChecked'] == 1, // Convert integer back to boolean
    );
  }
}
