// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjC_m_zuCYjQ6Jy2G7vJNFoXPb-pL50Dc',
    appId: '1:749965420775:android:6d44fda255d250dcbe5a42',
    messagingSenderId: '749965420775',
    projectId: 'taskmanager-3f5f8',
    storageBucket: 'taskmanager-3f5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByUd7y0dZWFJnAmV_HaOFzWGNdJMj74zA',
    appId: '1:749965420775:ios:4071c28375c1992abe5a42',
    messagingSenderId: '749965420775',
    projectId: 'taskmanager-3f5f8',
    storageBucket: 'taskmanager-3f5f8.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDzOa2g-Dk-XxEkJgdG7Fug572PlWzZ-3s",
      authDomain: "taskmanager-3f5f8.firebaseapp.com",
      projectId: "taskmanager-3f5f8",
      storageBucket: "taskmanager-3f5f8.firebasestorage.app",
      messagingSenderId: "749965420775",
      appId: "1:749965420775:web:905467ed5d9a6fa3be5a42");

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByUd7y0dZWFJnAmV_HaOFzWGNdJMj74zA',
    appId: '1:749965420775:ios:504993ea76a5e4c5be5a42',
    messagingSenderId: '749965420775',
    projectId: 'taskmanager-3f5f8',
    storageBucket: 'taskmanager-3f5f8.firebasestorage.app',
    iosBundleId: 'com.example.databaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzOa2g-Dk-XxEkJgdG7Fug572PlWzZ-3s',
    appId: '1:749965420775:web:7269ff14cb9839e4be5a42',
    messagingSenderId: '749965420775',
    projectId: 'taskmanager-3f5f8',
    authDomain: 'taskmanager-3f5f8.firebaseapp.com',
    storageBucket: 'taskmanager-3f5f8.firebasestorage.app',
  );
}
